//
//  LoggerGenerator.swift
//  Logs
//
//  Created by Brianna Zamora on 3/23/24.
//

import Foundation
import ArgumentParser

@main
struct LoggerGenerator: AsyncParsableCommand {
    @Argument(transform: {
        URL(filePath: $0, directoryHint: .isDirectory)
    }) var outputDirectory: URL

    @Argument var moduleName: String

    @Argument var defaultSubsystem: String

    func run() async throws {
        let loggerFile = """
        ///  
        ///  Logger.swift
        ///  \(moduleName)
        ///
        ///  Generated by LoggerGenerator on \(Date.now.formatted(date: .numeric, time: .omitted)) at \(Date.now.formatted(date: .omitted, time: .shortened)).

        import Foundation
        import os

        extension Logger {
            init(category: String) {
                self.init(
                    subsystem: (Bundle.main.bundleIdentifier ?? "App") + ":\(defaultSubsystem)",
                    category: "\(moduleName):\\(category)"
                )
            }
        }
        """

        try loggerFile.data(using: .utf8)?.write(to: outputDirectory)
    }
}
